//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using NC.Wpf.EntityFrameworkCore;
//using Volo.Abp.EntityFrameworkCore;

//#nullable disable

//namespace NC.Wpf.App.Migrations
//{
//    [DbContext(typeof(NCWpfMigrationsDbContext))]
//    [Migration("20240517063353_Initial")]
//    partial class Initial
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
//                .HasAnnotation("ProductVersion", "8.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("NC.Wpf.Domain.Sample", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .IsRequired()
//                        .HasMaxLength(40)
//                        .HasColumnType("nvarchar(40)")
//                        .HasColumnName("ConcurrencyStamp");

//                    b.Property<DateTime>("CreationTime")
//                        .HasColumnType("datetime2")
//                        .HasColumnName("CreationTime");

//                    b.Property<Guid?>("CreatorId")
//                        .HasColumnType("uniqueidentifier")
//                        .HasColumnName("CreatorId");

//                    b.Property<string>("ExtraProperties")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)")
//                        .HasColumnName("ExtraProperties");

//                    b.Property<bool>("IsDeleted")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bit")
//                        .HasDefaultValue(false)
//                        .HasColumnName("IsDeleted");

//                    b.Property<DateTime?>("LastModificationTime")
//                        .HasColumnType("datetime2")
//                        .HasColumnName("LastModificationTime");

//                    b.Property<Guid?>("LastModifierId")
//                        .HasColumnType("uniqueidentifier")
//                        .HasColumnName("LastModifierId");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(20)");

//                    b.Property<string>("Type")
//                        .HasColumnType("nvarchar(20)");

//                    b.HasKey("Id");

//                    b.ToTable("TSamples");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
